### ISSUE TITLE
[URGENT] navigating directly to a video link (#episode-one for instance) does not redirect to #optincta

### ISSUE THREAD

**Issue by Dan-Halcyon** [HalcyonBio/halcyon.bio#20]
If someone has not put in their email yet, they are not redirected when trying to access videos by the link https://neuromethod.halcyon.bio/#episode-one / https://neuromethod.halcyon.bio/#episode-two / three / four 
this was working a few weeks ago maybe before we added the additional code for the other episodes and it was just set for episode one or the trailer?

**Comment by davidtai** [comment]
only worked for episode 1

**Comment by Dan-Halcyon** [comment]
it would be helpful if you mentioned that you fixed it and what you did so when I add episode 3 we don't have the same issue. 
You added 
   if window.location.hash == '#episode-two' && !@submitted
        window.location.hash = '#optinctb'

shouldn't this be optincta? is that a typo?

**Comment by davidtai** [comment]
Yeah that's a typo, I fixed it and added another for episode 3.

You just need to copy the line and update with the episode id
if window.location.hash == '#episode-four' && !@submitted
window.location.hash = '#optincta'
