### ISSUE TITLE
[URGENT] linking directly to a episode not working properly

### ISSUE THREAD

**Issue by Dan-Halcyon** [HalcyonBio/halcyon.bio#23]
navigating directly to https://neuromethod.halcyon.bio/#episode-two or https://neuromethod.halcyon.bio/#episode-two etc. doesn't show video like it should 
to replicate just go directly to the link
to see how it should look upon landing on page click on the video 1, 2, or 3 thumbnail for it to reveal the video

**Comment by davidtai** [comment]
this was never added

**Comment by Dan-Halcyon** [comment]
i swear this definitely worked at some point. this is why I put in all of the div-to-target:target display block/none stuff. it worked when going to the link or when clicking on it. closing it and saying this wasn't added doesn't help solve the problem. how can we get this working properly

**Comment by Dan-Halcyon** [comment]
you can see it work for a second then something overrides it and it gets hidden again.

**Comment by davidtai** [comment]
I did fix it, when I closed it.  I'll take another look.

**Comment by davidtai** [comment]
worked on FF/Chrome/Safari on IOS
