### ISSUE TITLE
product description not showing in backend 

### ISSUE THREAD

**Issue by Dan-Halcyon** [HalcyonBio/halcyon.bio#29]
it shows up on front end but not backend https://dash2.hanzo.io/product/P7c8KkgxUEGRO0/

**Comment by Dan-Halcyon** [comment]
I updated description to the below and it still just says "test" on front end: 

Elite Performance Upgrade for a second person. Includes: 
- 5 Coaching calls with Ron and Performance Psychologist
- Neuromethod360 12 week guide
- 12 week supply of Halcyon
- Cognitive Enhancement Guide 
- Neuromethod360 Private Facebook Group
- Bonus: Halcyon VIP event - meet with Ron and Halcyon Team and Halcyon Ambassadors at exclusive party in your choice of California or New York

**Comment by Dan-Halcyon** [comment]
I can’t save this new product description I have that's in HTML: 
`<h4 class="product-title">Neuromethod360</h4>
                <p>12-week interactive program for boosting mental performance and creating healthy habits for your brain, featuring proven techniques and habits from our Performance Psychologist, as well as the leading Memory Expert, Ron White.  </p>
                <p class="package-details"><i class="frfa checkmark fa fa-2x fa-check-circle"></i> <i class="srfa gift fa fa-envelope-open-o" aria-hidden="true"></i> 12 week program <strong>($299 value) </strong><br><i class="frfa checkmark fa fa-2x fa-check-circle"></i> <i class="srfa gift fas fa-capsules"></i>12 week supply of Halcyon <strong>($270 value) </strong><br><i class="frfa checkmark fa fa-2x fa-check-circle"></i> <i class="srfa gift fas fa-book-open"></i>Cognitive Enhancement Guide <strong>($88 value) </strong><br><i class="frfa checkmark fa fa-2x fa-check-circle"></i> <i class="srfa gift fa fa-users"></i>Neuromethod360 Private Facebook Group Membership<br><i class="frfa checkmark fa fa-2x fa-check-circle"></i> <i class="srfa gift fa fa-gift "></i> One out of the first 100 will be selected for 1-on-1 memory coaching also <strong>reg. $18,000 </strong><br><br>
                </p>
                <p class="limit-notice">
                  Space is extremely limited as this is a highly interactive 12 week program. Only
                  300 spots are available for October access, for those who do not make it into
                  the first 300, the second cohort of 1000 students will begin in December.
                </p>`
also what's status with cloudflare - ping Zach? need this working correctly ASAP so I can review

**Comment by tmesser** [comment]
Cloudflare has been set to properly expire the cache when updating these product descriptions now, and this has worked for a good half dozen updates now. Pretty safe to say this one is resolved, at least for the moment.
