### ISSUE TITLE
update countdown to include minutes and tenths of a second

### ISSUE THREAD

**Issue by Dan-Halcyon** [HalcyonBio/halcyon.bio#32]
add 10ths of second and minutes to countdown timer in checkout-flow.coffee and show it on 
checkout.pug
h2.countdown 02 : { getSeconds() } : 99
replace 02 and 99 placeholders with minutes and tenths
update to 5 min for toUpsell1 and 1 min for toUpsell2/toUpsell3

help with countdown on /index too please - need tenths of a second there too - see line 44 and 275
I put it there (subtitle2) so it's easy to see. it's currently hidden currently so inspect element and turn off display;none if you need to see it

**Comment by davidtai** [comment]
works now

**Comment by Dan-Halcyon** [comment]
you forgot this:

help with countdown on /index too please - need tenths of a second there too - see line 71/72 and 275
note that

on 72 is hidden currently so inspect element and turn off display;none if you need to see it

**Comment by Dan-Halcyon** [comment]
you forgot this:

help with countdown on /index too please - need tenths of a second there too - see line 71/72 and 275
note that

help with countdown on /index too please - need tenths of a second there too - see line 44 and 275
I put it there (subtitle2) so it's easy to see. it's currently hidden currently so inspect element and turn off display;none if you need to see it

**Comment by davidtai** [comment]
Can you flesh this out more?  What does it do?  What does it countdown to?  We've never talked about this before.

**Comment by Dan-Halcyon** [comment]
@davidtai 
this just simply counts down to 10 days from when we "open cart" (I need to update the end date but that's what it does) when it expires nothing automatic happens, I will just change what it displayed manually.
