### ISSUE TITLE
videos still playing when not viewable

### ISSUE THREAD

**Issue by Dan-Halcyon** [HalcyonBio/halcyon.bio#33]
video 3, play, switch to video 2 - video 3 keeps playing

**Comment by davidtai** [comment]
no repro

**Comment by Dan-Halcyon** [comment]
click video 1, 2, or 3. play it. click the watch trailer button. videos still play.

**Comment by Dan-Halcyon** [comment]
didn't mean to close

**Comment by Dan-Halcyon** [comment]
unable to replicate anymore, appears fixed.
