### ISSUE TITLE
optin not auto focusing on new popover optin

### ISSUE THREAD

**Issue by Dan-Halcyon** [HalcyonBio/halcyon.bio#35]
click a thumbnail on an incognito window on /index and a popover optin will appear over thumbnails but it isn't auto focusing on the field anymore. 

in video-form is the code that should make this happen

requestAnimationFrame =>
        if window.location.hash == '#optincta'
          $(@root).find('.main-optin input[name="email"]').focus()

      window.addEventListener 'hashchange', =>
        requestAnimationFrame =>
          if window.location.hash == '#optincta'
            $(@root).find('.main-optin input[name="email"]').focus()

the new popover uses .main-optin and the old one, still visible on the page, no longer does so it doesn't have trouble knowing which one, so not sure why it's not working

**Comment by davidtai** [comment]
improved by using scrollIntoFiew

**Comment by Dan-Halcyon** [comment]
close but due to the fixed header, you need to focus on the container, thumb-popover-optin-cont so that the opt in is in view and not stuck behind header
![cursor_and_halcyon___neuromethod360_masterclass_with_ron_white](https://user-images.githubusercontent.com/41127302/45518396-a16a6900-b7b1-11e8-9faa-6436abbd7868.jpg)
