### ISSUE TITLE
add/fix tooltip

### ISSUE THREAD

**Issue by Dan-Halcyon** [HalcyonBio/halcyon.bio#37]
in checkout.pug
my tooltip isn't working
need one for over Halcyon
ctrl+f some of this and you'll see what I tried to do - css is in launch-squeeze.styl (I know it should be in checkout.styl)
  h2.text-center.ug-title.tooltip 6 months of #[span(style="text-decoration:underline;text-decoration-style:dotted;") Halcyon] <i class="info fas fa-info-circle"></i>
                .top 
                  | Delivered automatically as part of your order. 
                  | HALCYON™ featuring DOPA-XR™ extended-release Theacrine, is a proprietary, patent-pending formula designed to support an elevated mental state. 
                  |
                  br
                  |Each ingredient is FDA compliant and clinically demonstrated to support key aspects of human cognition, including memory, focus, and motivation. †

**Comment by davidtai** [comment]
I'm not sure where or what this tool tip is supposed to be.

Can you provide any details?  I don't see the CSS for it.

**Comment by Dan-Halcyon** [comment]
@davidtai sorry I removed it last night cause it wasn't working correctly at all. We just want h2.text-center.ug-title.tooltip 6 months of #[span(style="text-decoration:underline;text-decoration-style:dotted;") Halcyon]  
to be a tooltop on click or hover. 
the content of the tooltip is: 
p. 
| Delivered automatically as part of your order.
| HALCYON™ featuring DOPA-XR™ extended-release Theacrine, is a proprietary, patent-pending formula designed to support an elevated mental state.
|
br
|Each ingredient is FDA compliant and clinically demonstrated to support key aspects of human cognition, including memory, focus, and motivation. †

i think that's straight forward but call me on slack if not
