### ISSUE TITLE
when you move to from step (info > upsell stage) to step, page is not at top

### ISSUE THREAD

**Issue by Dan-Halcyon** [HalcyonBio/halcyon.bio#38]
recreate by putting in info and going to upsell stage 1 - page will be scrolled half way down

**Comment by davidtai** [comment]
Can we figure out a way to avoid too much scrolling on the upsell side?  There is a large amount of content that's going to make it hard to make sales on mobile

**Comment by Dan-Halcyon** [comment]
@davidtai I know on mobile there is a bit to scroll through as far as upsells are concerned. I don't have a solution. let's just make sure it starts at the top of the page.
