### ISSUE TITLE
back to two step for checkout

### ISSUE THREAD

**Issue by Dan-Halcyon** [HalcyonBio/halcyon.bio#39]
we still wanted the portion of checkout where they put in their info to be in two steps like it normally is so we can collect more emails of people that abandon cart

**Comment by davidtai** [comment]
Are you sure about this?  We can enable cart info to do the same thing.

**Comment by Dan-Halcyon** [comment]
@davidtai what do you mean enable cart info? so if they put in email then leave page we still capture? If so, how can we send them a abandon cart email then?

**Comment by davidtai** [comment]
you have to do it manually since sendgrid has no way of doing that.
