### ISSUE TITLE
Affiliate link not working when signing up on Mobile

### ISSUE THREAD

**Issue by Dan-Halcyon** [HalcyonBio/halcyon.bio#41]
On mobile for the affiliate account via /partner, the copy button and the affiliate link are both undefined 
 This is not the case via desktop

**Comment by tmesser** [comment]
The affiliate link is working fine after some work on this, but the copy button is in a permanent 'copied' state and does not function properly. Looking into this.

**Comment by tmesser** [comment]
Turns out even that much was a caching issue. This is resolved.
